### PR TITLE
Add basic Azure setup with example and notes.

### PR DESCRIPTION
**Pull request by StylusEaterChef**
I created a basic network setup in Azure and by default leveraged Azure for the WSUS example. Improved the documentation and gave some examples on how to override a few things. Seems the kitchen-azurerm driver could use some love to reduce reliance on ARM pre-deployment templates (it has a lot of 'sharp edged' default names that make resource collisions a real thing).

### CODE REVIEW

**Comment by jmassardo** [comment]
@StylusEaterChef Can you provide some more details about the benefits of adding the additional arm template versus allowing the nodes to use the public IP address?

**Comment by StylusEaterChef** [comment]
> @StylusEaterChef Can you provide some more details about the benefits of adding the additional arm template versus allowing the nodes to use the public IP address?


Yes. Ideally we should be doing this kind of work in a private virtual network with no public addresses. I created the template to spark a few lines of discussion -- kind of hard to explain in a few words but I'll give it a try. 

If we want to keep this as simple as possible and be sure to mention this is just a starting point then I agree it makes sense to have public addresses and move on.

But, being new to the group, I'm also left wondering where the lines are with regard to best practices, usable code and pure demos.

For example, do we have "cloud native" boilerplate examples with best practices defined with working code that we could then layer this on top of? 

Does it even make sense to work towards reusable components for all people to pull from to remove repeat work for each of us? 

Should we even try to work our way up from the basics by eventually deprecating things like the complicated AWS HA example through small improvements added to things like this patch_management repository along the way?

**Comment by jmassardo** [comment]
I understand the desire to make it more secure, however, since this is a reference pattern and not a directly consumable solution, I think we'll end up with easier to digest examples (and less tech debt/maintenance) if we keep the examples as simple as possible.

**Comment by StylusEaterChef** [comment]
@jmassardo I'll adjust this PR to pull out the wsus/windows example and use Public IPs then migrate the private configuration over to the examples repository. @danielcbright and I are meeting today to discuss a kitchen oriented Azure example based on his existing work. Thanks for the comments.

**Pull request closed without merging**
